### PR TITLE
LTD-4597-celery-healthcheck

### PR DESCRIPTION
**Pull request by seijihg**
https://uktrade.atlassian.net/browse/LTD-4597

### CODE REVIEW

**Comment by stuaxo** [comment]
I mean.. it LGTM, so provisionally approving - I guess the work is really done in the healthcheck module - is that a DBT one ?

Wonder what it does, and does it check important bits like timeouts connecting to Celery.

**Review by stuaxo — APPROVED** [review]

**Review by currycoder — COMMENTED** [review]
Have you proven that this works on an environment?  It might be an idea to e.g. deploy this to demo -> scale celery cloudfoundry workers to 0 instances -> see that the healthcheck endpoint complains about celery

**Comment by seijihg** [comment]
> Have you proven that this works on an environment? It might be an idea to e.g. deploy this to demo -> scale celery cloudfoundry workers to 0 instances -> see that the healthcheck endpoint complains about celery

actually good idea lemme deploy somewhere and test it out

**Review by hnryjmes — COMMENTED** [review]
as brendan has said above, if you can test on a dev environment and then make another comment here with your findings (i.e. it works as expected) I'm happy to approve after that

**Comment by seijihg** [comment]
> Have you proven that this works on an environment? It might be an idea to e.g. deploy this to demo -> scale celery cloudfoundry workers to 0 instances -> see that the healthcheck endpoint complains about celery

yes it does fail when celery worker is 0 on dev2

**Review by hnryjmes — APPROVED** [review]

**Review by currycoder — APPROVED** [review]

**Pull request merged**
