### PR TITLE
LTD-4197: Fix CodeQL warnings

### PR DESCRIPTION
**Pull request by saruniitr**
### Change description

Replace exception message with generic error messages to avoid exposing internal details

[LTD-4197](https://uktrade.atlassian.net/browse/LTD-4197)

[LTD-4197]: https://uktrade.atlassian.net/browse/LTD-4197?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by kevincarrogan — APPROVED** [review]

**Review by depsiatwal — COMMENTED** [review]
lgtm but  codecode is missing a line

**Comment by saruniitr** [comment]
@depsiatwal actually I added a test for that but it is still complaining for some reason

**Comment by saruniitr** [comment]
> @depsiatwal actually I added a test for that but it is still complaining for some reason

actually that exception handling is not required, will update

**Review by depsiatwal — APPROVED** [review]
lgtm

**Pull request merged**
