### PR TITLE
Match cf linux in docker e2e

### PR DESCRIPTION
**Pull request by kevincarrogan**
### Aim

[LTD-](https://uktrade.atlassian.net/browse/LTD-)

### CODE REVIEW

**Comment by stuaxo** [comment]
Not a blocker:  
consider the deadsnakes ppa, it should keep build times reasonable if that's a thing for pyenv.

```
sudo add-apt-repository ppa:deadsnakes/ppa
sudo apt install python3.8 python3.9
```

https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa

The PPA should be OK, it's been the ubuntu place for different python versions for a number of years

**Comment by hnryjmes** [comment]
I can see you've updated commands in a few places to use pipenv run, e.g. `./manage.py ingest_ui_test_sanctions` becomes `pipenv run ./manage.py ingest_ui_test_sanctions`

We also should do this for the docker commands here for completeness sake:

https://github.com/uktrade/lite-api/blob/dev/makefile#L16

I only know this because I pulled this branch and tried to run `make doc-migrate` locally and it didn't work, but it does work if you exec into the container and then do `pipenv shell` and `python manage.py migrate`. I guess changing those makefile commands to use `pipenv run` would have the same effect, because it would make sure that pipenv was happy first

**Review by hnryjmes — APPROVED** [review]
Approved, have also made a suggestion about the makefile in my other comment

**Comment by hnryjmes** [comment]
@stuaxo I am not sure I agree with the deadsnakes suggestion just because the point of this exercise is to make our dev environments as similar to the cf environments as reasonably possible, so using pipenv here seems like it contributes to that aim

**Comment by kevincarrogan** [comment]
> I can see you've updated commands in a few places to use pipenv run, e.g. `./manage.py ingest_ui_test_sanctions` becomes `pipenv run ./manage.py ingest_ui_test_sanctions`
> 
> We also should do this for the docker commands here for completeness sake:
> 
> https://github.com/uktrade/lite-api/blob/dev/makefile#L16
> 
> I only know this because I pulled this branch and tried to run `make doc-migrate` locally and it didn't work, but it does work if you exec into the container and then do `pipenv shell` and `python manage.py migrate`. I guess changing those makefile commands to use `pipenv run` would have the same effect, because it would make sure that pipenv was happy first

I'll make another PR to fix this.

**Review by seijihg — APPROVED** [review]

**Pull request merged**
