### PR TITLE
Upgrade lite-api to python 3.8

### PR DESCRIPTION
**Pull request by hnryjmes**
[LTD-4209](https://uktrade.atlassian.net/browse/LTD-4209)

[LTD-4209]: https://uktrade.atlassian.net/browse/LTD-4209?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by hnryjmes** [comment]
@kevincarrogan I am requesting your review mainly on the `Pipfile` - could you have a quick check to see if it looks alright, thanks

**Review by Tllew — APPROVED** [review]
Looks good to me

**Review by depsiatwal — APPROVED** [review]
lgtm

**Comment by hnryjmes** [comment]
@kevincarrogan I actually might need you to do your magic thing of ignoring the codecov error to merge this one, I can explain in more detail if need be, but basically - I tried fixing the linting errors in a sensible way, that broke a whole load of stuff, so I decided to opt for just adding `# noqa` comments instead, and now this has fixed the linting but set off codecov

as I want to get 3.8 working on lite-api I'd rather just we ignore this and move on without worrying about fixing any more CI errors - but that's your call to make, would like your opinion on what we should do here :)

**Pull request merged**
